### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BiancaZYCao** [BiancaZYCao/intelligent-call-center-assistant#1]
# Demo TODO list

- [x] #2
- [x] #6
- [x] improve timeline
- [x] improve topic modelling keywords display: remove duplicates @siopoh 
- [x] improve topic modelling advanced  @siopoh 
- [ ] improve frontend @huiwentang 
- [x] Add: UI summary page: bar charts (last 7 days records) only PLP
- [x] Update: Topic Modelling UI html
- [ ] Intergrate and fix score aggr 
- [x] move transcripts to right side reply hint
